baseURL = 'https://mu7889yoon.github.io/mu7889yoon/'
languageCode = 'ja-jp'
title = 'よ〜んの雑記'
theme = 'm10c'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
[[params.social]]
  icon = "brand-github"
  name = "Github"
  url = "https://github.com/mu7889yoon"