baseURL = 'https://mu7889yoon.github.io/mu7889yoon/'
languageCode = 'ja-jp'
title = 'よ〜んの雑記'
theme = 'm10c'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

[params]
  author = 'mu7889yoon / yuta nakamura'
  avatar = 'public/avater.jpg'
  description = '''
    Live in Kyoto(Japan)
    Osaka Electro-Communication University
    Bachelor of Science in Information Technology
    2025 Japan AWS Jr. Champions
  '''
[[params.social]]
  icon = "brand-github"
  name = "Github"
  url = "https://github.com/mu7889yoon"
[[params.social]]
  icon = "brand-x"
  name = "X"
  url = "https://twitter.com/Tesla_yoon"
