baseURL = 'https://mu7889yoon.github.io/'
languageCode = 'ja-jp'
title = 'よ〜んの雑記'

[markup.goldmark.renderer]
  unsafe = true

[services]
  [services.googleAnalytics]
    id = 'G-9NZ6DBN19T'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
  [[module.imports]]
    path = 'github.com/vaga/hugo-theme-m10c'

[params.style]
  darkestColor = "#0b132b"
  darkColor = "#1c2541"
  lightColor = "#cfdbd5"
  lightestColor = "#e8eddf"
  primaryColor = "#d99124ff"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 2
    
[params]
  author = 'mu7889yoon / yuta nakamura'
  description = '　'
  avatar = 'mu7889yoon/image.png'
  menu_item_separator = '<br>'
  twitterSite = '@Tesla_yoon'
  twitterCreator = '@Tesla_yoon'
  defaultOgImage = 'mu7889yoon/image.png'
[[params.social]]
  icon = 'brand-github'
  name = 'Github'
  url = 'https://github.com/mu7889yoon'
[[params.social]]
  icon = 'brand-x'
  name = 'X'
  url = 'https://twitter.com/Tesla_yoon'
[[params.social]]
  icon = 'brand-speakerdeck'
  name = 'speakerdeck'
  url ='https://speakerdeck.com/mu7889yoon'
[[params.social]]
  icon = 'brand-connpass'
  name = 'connpass'
  url = 'https://connpass.com/user/mu7889yoon'
[[params.social]]
  icon = 'brand-builder-center'
  name = 'builder center'
  url = 'https://builder.aws.com/community/@mu7889yoon'
