baseURL = 'https://mu7889yoon.github.io/mu7889yoon/'
languageCode = 'ja-jp'
title = 'よ〜んの雑記'
theme = 'm10c'
author = 'mu7889yoon / tesla / Yuta Nakamura'
description = 'Live in Kyoto(Japan)\nOsaka Electro-Communication University\nBachelor of Science in Information Technology\n2025 Japan AWS Jr. Champions'
