baseURL = 'https://mu7889yoon.github.io/mu7889yoon/'
languageCode = 'ja-jp'
title = 'よ〜んの雑記'
theme = 'm10c'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

[params.style]
  darkestColor = "#0b132b"
  darkColor = "#1c2541"
  lightColor = "#cfdbd5"
  lightestColor = "#e8eddf"
  primaryColor = "#d99124ff"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2

[params]
  author = 'mu7889yoon / yuta nakamura'
  description = '　'
  avatar = 'mu7889yoon/image.png'
[[params.social]]
  icon = 'brand-github'
  name = 'Github'
  url = 'https://github.com/mu7889yoon'
[[params.social]]
  icon = 'brand-x'
  name = 'X'
  url = 'https://twitter.com/Tesla_yoon'
[[params.social]]
  icon = 'brand-speakerdeck'
  name = 'speakerdeck'
  url ='https://speakerdeck.com/mu7889yoon'
[[params.social]]
  icon = 'brand-connpass'
  name = 'connpass'
  url ='https://connpass.com/user/mu7889yoon'
